version: "3.5"
name: "Draftly-services"

services: 
  db:
    image: postgres
    restart: always
    container_name: Draftly-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: super-productive
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "8010:5432"

volumes:
  database-data:
